### ISSUE TITLE
Update progress during startup and loading games

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#27]
Currently, startup and heatmap take some time to complete. Both display a popup, but this could be replaced by a progressbar with some usefull information. This would reduce the perceived waiting time and shows the user that the application is actually working. 

[enhancement]

**Comment by stevens68** [comment]
yes, both tasks take some time. valid point.
On my 7-year old non-GPU notebook: 20 sec to initialize the bots, ~35 seconds to calculate the heatmap.

initialization of bots:
here it's a little tricky because we do not loop over something but have to wait for tensorflow to read the network and initialize its machinery. We'd have to move the initialization in a thread to be able to update the spinner / progressbar. Not sure if it's worth the effort.

heatmap calculation:
I'd like to move that one to a thread and re-use the progress bar that we already have; and also be able to use cancel the button.

**Comment by stevens68** [comment]
Heatmap time: 
If we switch to a "P"-Heatmap, there won't be any significant waiting time

Start-Up time: 
What we could do is to update the pop-up  between bot 1 and 2 (~ 70% of the time is for bot 1 I believe)
We could also remove redundancy  and let both bots share one NNEvaluater if the model path 1 and 2 is the same, which is true unless you come up with another network.

Load game time:
I removed the GUI update between moves during replay to save time; Replay is still necessary to update the eval history; here we also could think about updating the popup in case of lengthy games.

**Comment by agtoever** [comment]
Progress during startup: #39 
Progress during heatmap: not relevant anymore.

**Comment by stevens68** [comment]
Hi agtoever, thanks for your PR!

I like the bar and the steps/messages but as I'm more in favor of a plain, elementary UI I omitted the picture and the credits.
I agree with the load-game-times: they are fast enough.
Regards, stevens68

**Comment by stevens68** [comment]
Implemented, merged in PR#43
