### ISSUE TITLE
Let the bot make mistakes / implement "weaker" bot player

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#50]
>  the most important: TB always wants to play a perfect game (even using pure P-values). When you play against it you’ll almost never face a bad move. That means, that there is no chance to simulate a play like with a weaker player. For a beginner like me, it’s impossible to train progressively. In games against human I can try to use what I know now and win if my opponent makes mistakes. Being able to recognize such mistakes is crucial for a progress. With TB is normally impossible.

I think there are some options to tune the bot player's performance. Right now, the bot always plays the best move from the policy (highest P-value). Instead, the bot could choose another move from the policy with a lower P-value. The "favourability" for the highest P could be easily manipulated with a parameter r (e.g.: 0.0 = "random" move from policy moves and 1.0 = always choose highest P-value). random.choices() has a weight parameter. The P-values to the power of that parameter r could be the weight... r=0 would make all policy moves equal probable.

[source](https://www.littlegolem.net/jsp/forum/topic2.jsp?forum=55&topic=429)

**Comment by agtoever** [comment]
Started working on this one.

**Comment by Twixtfanatic** [comment]
Instead of weaker versions, how about implementing row handicapping? The smallest handicap is to allow one player to move first without being swapped. So a central first move would be a good move. Beyond that, one dimension of the board is reduced. The weaker player moves first without swap AND has less distance to cross.

I would not advise allowing the player who moves second to receive any kind of row handicap. For one thing, it complicates the rules unnecessarily. Also, it would not be obvious how to step between these two methods. If one player moves first but the second player has one less row to cross, which side is getting a handicap?

This has been shown to be a very granular way to find a handicap between two specific players where each side wins about half the time. Another advantage is, this would allow for data to accumulate regarding how much row handicap is appropriate for a specific difference in Elo rating, which in turn might some day result in greater accuracy in rating handicap tournaments.

This would likely necessitate generating a new engine from scratch for each handicap step, but IMO it would generate more benefit than imposing restrictions on the engine itself.

**Comment by agtoever** [comment]
@stevens68 : could you please take a look at my work-in-progress in [my adjust_bot_level_#50 branch](https://github.com/agtoever/twixtbot-ui/tree/adjust_bot_level_%2350)? It's a first rough implementation with just one strength parameter for both bots (0=weak; 1=best), set as a global constant in tbui.py, but adjusting that parameter works. It would be great if you could comment on the direction I'm going with this.

**Comment by stevens68** [comment]
sure, agtoever. Will try to have a look the next days. Thanks!

**Comment by genmeblog** [comment]
@Twixtfanatic I think handicap is something different than weak bot. Strong bot with handicap still will be strong. So maybe handicap could be implemented but as an additional feature rather than replacement for weak bot.

**Comment by stevens68** [comment]
Implemented a "Level" parameter in [PR#94](https://github.com/stevens68/twixtbot-ui/pull/94)

**Comment by Twixtfanatic** [comment]
Maybe this is a difference in philosophy. Please do continue with reducing
the quality of the bot's play if you wish. I just don't understand what is
*inherently* wrong with a strong bot. Shogi players will attest to the fact
that a graded handicap system is an excellent way to learn Shogi concepts.
Once you beat a strong bot at X handicap, you will know that you have
absolutely learned certain ideas and patterns that you need to know. But
defeating an arbitrarily weakened bot might not carry any such guarantee.

Do you believe that a strong bot will still be difficult to defeat
regardless of the handicap? Take a look at the attached image. This is the
maximum handicap available on Game Center. The weaker player also moves
first in this handicap. My point is that row handicapping is granular. The
process of learning is broken down into steps. Find a handicap where you
beat a strong bot half the time. Win three consecutive games to advance to
the next level.

**Comment by stevens68** [comment]
Closing this issue - though the discussion is interesting (an may be continued at littlegolem).

I personally like neither row-handicapping nor any other weakening and will probably never make use of the new parameter 
("if the bot is too strong - you're just to weak"). 
But I don't want that anybody doesn't use twixtbot-ui because of frustration ;-)

Thanks for your comments!
